name: Instances
author: Vestri
description: Instances
version: 0.6
api-version: 1.15
main: instance.java.Instances
depend: [PlayertoSql, WorldGuard, WorldEdit]
permissions:
  instances.admin:
    description: admin
    default: op
  instances.player:
    description: player
    default: op
commands:
  ijoin:
    description: join instance
    usage: /ijoin [playername] <instancename>
  ileave:
    description: leave instance
    usage: /ileave [playername]
  iready:
    description: ready check
    usage: /iready [playername]
  istartreadycheck:
    description: start ready check
    usage: /istartreadycheck